/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package nl.tudelft.sem.template.example.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import nl.tudelft.sem.template.api.ApiUtil;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-12-04T18:49:43.383449300+01:00[Europe/Amsterdam]")
@Validated
@Tag(name = "public book statistics", description = "provide statistics for books that are visible to all users")
public interface GetPublicInteractionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /getPublicInteractions/{bookId}/{userId} : how many reviews the book has
     * returns the amount of reviews, so that users can quickly see the interactions and popularity of the book
     *
     * @param bookId the book to return number of reviews (required)
     * @param userId the user that requests number of reviews (required)
     * @return Successful operation (status code 200)
     *         or cannot find book (status code 400)
     */
    @Operation(
        operationId = "getPublicInteractionsBookIdUserIdGet",
        summary = "how many reviews the book has",
        description = "returns the amount of reviews, so that users can quickly see the interactions and popularity of the book",
        tags = { "public book statistics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Long.class))
            }),
            @ApiResponse(responseCode = "400", description = "cannot find book")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getPublicInteractions/{bookId}/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Long> getPublicInteractionsBookIdUserIdGet(
        @Parameter(name = "bookId", description = "the book to return number of reviews", required = true, in = ParameterIn.PATH) @PathVariable("bookId") Long bookId,
        @Parameter(name = "userId", description = "the user that requests number of reviews", required = true, in = ParameterIn.PATH) @PathVariable("userId") Long userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "250";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
